project_id = "ctfqkbbauvznzmznmjdt"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[functions.process-bet]
verify_jwt = false

[functions.confirm-transaction]
verify_jwt = false

[functions.get-user-bets]
verify_jwt = false

[functions.monitor-escrow]
verify_jwt = false

[functions.oracle-resolver]
verify_jwt = false

[functions.resolve-prediction]
verify_jwt = false

[functions.update-profile]
verify_jwt = false

[functions.fetch-trending-topics]
verify_jwt = false

[functions.get-public-bets]
verify_jwt = false

[functions.add-comment]
verify_jwt = false

[functions.validate-session]
verify_jwt = false

[functions.paybutton-webhook]
verify_jwt = false

[functions.create-session]
verify_jwt = false

[functions.send-payouts]
verify_jwt = false

[functions.admin-secret-login]
verify_jwt = false
